config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/pricing',   to: 'static_pages#pricing'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/features',  to: 'static_pages#features'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def features
  end

  def pricing
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag('CompanyLogo.png', size: "200x200"), root_path %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Features', features_path %></li>
      <li><%= link_to 'Pricing', pricing_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Login', '#' %></li>
      <li><%= link_to 'Signup', '#' %></li>
    </ul>
  </div>
</nav>

app/views/static_pages/about.html.erb
This is the about page

app/views/static_pages/contact.html.erb
The contact page

app/views/static_pages/features.html.erb
The features page

app/views/static_pages/home.html.erb
<div id="page-content" class="container">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <%= image_tag("Homepage.jpg", style: "height: 300px; width: auto;") %>
    </div>
    <div class="col-sm-4">
      <h2 class="message-1">How valuable is retention?</h2>
        <h3 class="messages message-2">Know what's happening at your company now</h3>
    </div>
    <div class="col-sm-2">
    </div>
  </div>
</div>
<div id=adtext1 class="container">
  <div class="row">
    <h3 class="statement statement-1">A small application for a big impact . . .<h3>
  </div>
</div>
<div id=adpic1 class="container">
  <div class="row ad1pic">
    <%= image_tag("adpic1.jpg", style: "width:100%;") %>
  </div>
</div>
<div id=adtex2 class="container">
  <div class="row">
    <h3 class="statement statement-2">. . . We know that every employee matters</h3>
  </div>
</div>
<div class="container">
  <div class="row">
    <h3 class="counter" id="company-counter">550+ companies have already taken their first step</h3>
  </div>
</div>

app/views/static_pages/pricing.html.erb
This is the pricing page